### ISSUE TITLE
post-Spring Break checklist

### ISSUE THREAD

**Issue by beanumber** [vegahi/thesis#16]
- [x] write a paragraph summarizing existing literature about Citi Bike data
- [x] write a short paragraph summarizing research on bike-sharing in general
- [x] write a paragraph about the `citibike` package and how it fits into larger picture of `etl`, `dplyr`, etc.
- [x] write a paragraph about the importance of reproducible research
- [ ] get Shiny app running on RStudio Server (get URL, talk to Suzanne)
- [x] flesh out summary statistics tab on Shiny app
- [x] optimize code in Shiny app

Structure of thesis:
- Introduction
  - Motivation
  - Literature Review
  - My contribution
- Citi Bike and package
- Shiny app
- Modeling
- Conclusion
- Appendix
  - Summary statistics
